#!/bin/sh

# Uploads a file to AmeoTrack.  By default, it's set to be public and never expire.

RES=$(curl -s -F "password=$AMEOTRACK_PASSWORD" -F "file=@`pwd`/$1" https://ameo.link/u/upload)

# Copy the link to the clipboard
if [ -x "$(command -v xsel)" ]; then
	echo $RES | xsel --clipboard
fi

if [ -x "$(command -v pbcopy)" ]; then
	echo $RES | pbcopy
fi

GREEN='\033[1;32m'
NC='\033[0m' # No Color
echo "${GREEN}File successfully uploaded: $NC$RES"
echo "Link has been copied to the clipboard."
